name: Build & Test Example Projects
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        env:
          version: 4.2.1
        with:
          path: | 
            ~/.cache/bazel
          key: ${{ runner.os }}-{{ env.version }}-bazel-cache

      - name: Build artifacts
        run: bazel build //...

      - name: Run tests
        run: bazel test --test_output=errors --action_env="GTEST_COLOR=1" //...
